### PR TITLE
Add open method for Index class

### PR DESCRIPTION
**Pull request by NikolaosPapailiou**
This adds `open` method for `Index` class which can be used to open an index without knowing its `index_type`

Tested: unit-tests

### CODE REVIEW

**Review by Shelnutt2 — CHANGES_REQUESTED** [review]
Let's put together a proposal for this. I'd like to see consideration of just using the class constructor vs having a non-class member function for open. Having open on Index itself doesn't follow any existing pattern from other APIs and projects in TileDB.

**Comment by NikolaosPapailiou** [comment]
> Let's put together a proposal for this. I'd like to see consideration of just using the class constructor vs having a non-class member function for open. Having open on Index itself doesn't follow any existing pattern from other APIs and projects in TileDB.

Can you explain why this is not a pattern used in other TileDB projects? How is this different that `tiledb.open` for `Arrays` or `tiledbsoma.Experiment.open` for single cell `Experiment`?

**Comment by Shelnutt2** [comment]
> > Let's put together a proposal for this. I'd like to see consideration of just using the class constructor vs having a non-class member function for open. Having open on Index itself doesn't follow any existing pattern from other APIs and projects in TileDB.
> 
> Can you explain why this is not a pattern used in other TileDB projects? How is this different than `tiledb.open` for `Arrays` or `tiledbsoma.Experiment.open` for single cell `Experiment`?

Certainly. `tiledb.open` is a static function at the top level of a project, its not a static class member function. In SOMA, `tiledbsoma.open` is the preferred way and documented examples on opening the dataset. In TileDB-VCF we use `tiledbvcf.Dataset()` and handle it in a single constructor. There isn't a main method we propose that is a static class member for opening and decting the underlying type. Its important we aim for consistency across APIs so there is a general push to common UX. Either we should prompt the use of `Index` or a single top level open function.

**Comment by NikolaosPapailiou** [comment]
> > > Let's put together a proposal for this. I'd like to see consideration of just using the class constructor vs having a non-class member function for open. Having open on Index itself doesn't follow any existing pattern from other APIs and projects in TileDB.
> > 
> > 
> > Can you explain why this is not a pattern used in other TileDB projects? How is this different than `tiledb.open` for `Arrays` or `tiledbsoma.Experiment.open` for single cell `Experiment`?
> 
> Certainly. `tiledb.open` is a static function at the top level of a project, its not a static class member function. In SOMA, `tiledbsoma.open` is the preferred way and documented examples on opening the dataset. In TileDB-VCF we use `tiledbvcf.Dataset()` and handle it in a single constructor. There isn't a main method we propose that is a static class member for opening and decting the underlying type. Its important we aim for consistency across APIs so there is a general push to common UX. Either we should prompt the use of `Index` or a single top level open function.

Moved `open` to the top level of the project.

Concerning using the `Index` constructor, at the moment `Index` is an abstract class with concrete subclasses for each algorithm. In my understanding, this pattern can only use a factory method to instantiate concrete subclasses and can't use the abstract class constructor directly. To use the `Index` constructor we would need to reorganize our existing class and hierarchy structure. Let me know if you have a solution in mind for this to work.

**Comment by NikolaosPapailiou** [comment]
@Shelnutt2 is the current solution of `open` at the top level of the project consistent with other TileDB packages?

**Review by jparismorgan — APPROVED** [review]
Looks good to me and seems to simplify the user experience, though may want to confirm with Seth.

**Pull request merged**
