### PR TITLE
Use sklearn as default for kmeans until the C++ kmeans library is released in Docker images

### PR DESCRIPTION
**Pull request by NikolaosPapailiou**
Use sklearn as default for kmeans until the C++ kmeans library is released in Docker images

This is addressing the distributed execution errors discussed in https://app.shortcut.com/tiledb-inc/story/39163/fix-kmeans-distributed-ingestion

### CODE REVIEW

**Comment by jparismorgan** [comment]
Heads up you also may want to check the `km.n_threads_ = threads` line, I have been getting `AttributeError: 'KMeans' object has no attribute '_n_threads'`.

**Comment by ihnorton** [comment]
> Heads up you also may want to check the `km.n_threads_ = threads` line, I have been getting `AttributeError: 'KMeans' object has no attribute '_n_threads'`.

What version of sklearn?

**Review by ihnorton — APPROVED** [review]
Aside from Paris's question, this LGTM

**Comment by jparismorgan** [comment]
> > Heads up you also may want to check the `km.n_threads_ = threads` line, I have been getting `AttributeError: 'KMeans' object has no attribute '_n_threads'`.
> 
> What version of sklearn?

Here's my setup - looks like I'm on the most recent release: https://github.com/scikit-learn/scikit-learn/releases

```
(TileDB-Vector-Search-3) ~/repo/TileDB-Vector-Search-3/apis/python conda list                                                                                 1 ↵  ✹jparismorgan/random-sampling-distributed-kmeans 
# packages in environment at /opt/homebrew/anaconda3/envs/TileDB-Vector-Search-3:
#
# Name                    Version                   Build  Channel
astroid                   2.14.2           py39hca03da5_0  
attrs                     23.1.0                   pypi_0    pypi
ca-certificates           2023.11.17           hf0a4a13_0    conda-forge
certifi                   2023.11.17               pypi_0    pypi
cloudpickle               2.2.1                    pypi_0    pypi
colorama                  0.4.6              pyhd8ed1ab_0    conda-forge
dill                      0.3.7              pyhd8ed1ab_0    conda-forge
exceptiongroup            1.2.0              pyhd8ed1ab_0    conda-forge
importlib-metadata        7.0.0                    pypi_0    pypi
iniconfig                 2.0.0              pyhd8ed1ab_0    conda-forge
isort                     5.13.2             pyhd8ed1ab_0    conda-forge
joblib                    1.3.2                    pypi_0    pypi
lazy-object-proxy         1.6.0            py39h1a28f6b_0  
libcxx                    14.0.6               h848a8c0_0  
libffi                    3.4.4                hca03da5_0  
mccabe                    0.7.0              pyhd8ed1ab_0    conda-forge
ncurses                   6.4                  h313beb8_0  
numpy                     1.26.2                   pypi_0    pypi
openssl                   3.2.0                h0d3ecfb_1    conda-forge
packaging                 23.2               pyhd8ed1ab_0    conda-forge
pandas                    2.1.4                    pypi_0    pypi
pip                       23.3.1           py39hca03da5_0  
platformdirs              4.1.0              pyhd8ed1ab_0    conda-forge
pluggy                    1.3.0              pyhd8ed1ab_0    conda-forge
pyarrow                   14.0.2                   pypi_0    pypi
pylint                    2.16.2           py39hca03da5_0  
pytest                    7.4.3              pyhd8ed1ab_0    conda-forge
python                    3.9.18               hb885b13_0  
python-dateutil           2.8.2                    pypi_0    pypi
pytz                      2023.3.post1             pypi_0    pypi
readline                  8.2                  h1a28f6b_0  
scikit-learn              1.3.2                    pypi_0    pypi
scipy                     1.11.4                   pypi_0    pypi
setuptools                68.2.2           py39hca03da5_0  
six                       1.16.0                   pypi_0    pypi
sqlite                    3.41.2               h80987f9_0  
tblib                     1.7.0                    pypi_0    pypi
threadpoolctl             3.2.0                    pypi_0    pypi
tiledb                    0.25.0                   pypi_0    pypi
tiledb-cloud              0.11.2                   pypi_0    pypi
tiledb-vector-search      0.0.21.dev2+g9858c62.d20240112          pypi_0    pypi
tk                        8.6.12               hb8d0fd4_0  
tomli                     2.0.1              pyhd8ed1ab_0    conda-forge
tomlkit                   0.12.3             pyha770c72_0    conda-forge
typing-extensions         4.9.0                hd8ed1ab_0    conda-forge
typing_extensions         4.9.0              pyha770c72_0    conda-forge
tzdata                    2023.3                   pypi_0    pypi
urllib3                   2.1.0                    pypi_0    pypi
wheel                     0.41.2           py39hca03da5_0  
wrapt                     1.14.1           py39h1a28f6b_0  
xz                        5.4.5                h80987f9_0  
zipp                      3.17.0                   pypi_0    pypi
zlib                      1.2.13               h5a0b063_0  
```

**Comment by NikolaosPapailiou** [comment]
> Heads up you also may want to check the `km.n_threads_ = threads` line, I have been getting `AttributeError: 'KMeans' object has no attribute '_n_threads'`.

Fixed

**Pull request merged**
