### PR TITLE
Increment TileDB core version to 2.22.0

### PR DESCRIPTION
**Pull request by jparismorgan**
### What
Increment TileDB core version to 2.22.0.

### CODE REVIEW

**Comment by johnkerl** [comment]
Please also see https://github.com/TileDB-Inc/TileDB-Vector-Search/pull/291/files

**Comment by jparismorgan** [comment]
> @jparismorgan Please also see https://github.com/TileDB-Inc/TileDB-Vector-Search/pull/291/files

What specifically about it? Did I miss something here?

**Comment by johnkerl** [comment]
@jparismorgan 

```
johnkerl@exade[prod][main][TileDB-Vector-Search]$ rg '2\.21\.'
src/cmake/Modules/FindTileDB_EP.cmake
56:        fetch_prebuilt_tiledb(VERSION 2.21.1)
58:        fetch_source_tiledb(VERSION 2.21.1)

johnkerl@exade[prod][main][TileDB-Vector-Search]$ rg '0\.27\.'
pyproject.toml
22:    "tiledb>=0.27.0",

apis/python/requirements-py.txt
3:tiledb==0.27.0
```

**Comment by johnkerl** [comment]
P.S. @jparismorgan thanks for filling in! :)

**Review by ihnorton — APPROVED** [review]

**Comment by ihnorton** [comment]
wheel build check: https://github.com/TileDB-Inc/TileDB-Vector-Search/actions/runs/8725681006

**Comment by jparismorgan** [comment]
> wheel build check: https://github.com/TileDB-Inc/TileDB-Vector-Search/actions/runs/8725681006

Should I wait on this to complete before merging?

**Review by johnkerl — APPROVED** [review]

**Pull request merged**
