### PR TITLE
Enable tests in cibuildwheel step

### PR DESCRIPTION
**Pull request by dudoslav**
This PR aims to enable tests in `cibuildwheel` step. For now, windows tests are disabled and only Linux+MacOS tests are enabled. This change should not only install the produced wheel but also runs the tests in this repo.

Currently the pipeline fails on (for more detailed output https://github.com/dudoslav/TileDB-Vector-Search/actions/runs/7609245130/job/20720948938):
```
  =========================== short test summary info ============================
  FAILED ../../../project/apis/python/test/test_cloud.py::CloudTests::test_cloud_flat
  FAILED ../../../project/apis/python/test/test_cloud.py::CloudTests::test_cloud_ivf_flat
  ============ 2 failed, 35 passed, 59 warnings in 434.08s (0:07:14) =============
  ::endgroup::Testing wheel...
```

Edit 1.: Note that Python CI API workflow fails due to https://github.com/pypa/gh-action-pypi-publish/discussions/49

### CODE REVIEW

**Comment by dudoslav** [comment]
Latest CIBUILDWHEEL with tests: https://github.com/dudoslav/TileDB-Vector-Search/actions/runs/8470380414

**Comment by ihnorton** [comment]
@jparismorgan I don't understand this test failure

https://github.com/TileDB-Inc/TileDB-Vector-Search/actions/runs/8470358624/job/23207885020?pr=209#step:6:430

**Comment by jparismorgan** [comment]
I'm not sure about these:
```
FAILED test/test_index.py::test_delete_invalid_index - TypeError: string indices must be integers
FAILED test/test_index.py::test_delete_index - TypeError: string indices must be integers
```
But this seems like the root cause:
```
ERROR test/test_cloud.py::CloudTests::test_cloud_flat - ValueError: TILEDB_REST_TOKEN not set
ERROR test/test_cloud.py::CloudTests::test_cloud_ivf_flat - ValueError: TILEDB_REST_TOKEN not set
ERROR test/test_cloud.py::CloudTests::test_cloud_ivf_flat_random_sampling - ValueError: TILEDB_REST_TOKEN not set
```
I think we need to set `TILEDB_REST_TOKEN` on the `- name: Build wheels` job like we do at https://github.com/TileDB-Inc/TileDB-Vector-Search/blob/main/.github/workflows/ci-python.yml#L41:
```
        env:
          TILEDB_REST_TOKEN: ${{ secrets.TILEDB_CLOUD_HELPER_VAR }}
```

**Comment by dudoslav** [comment]
@jparismorgan We actually do set that variable (TILEDB_REST_TOKEN) here:

https://github.com/TileDB-Inc/TileDB-Vector-Search/pull/209/files#diff-14b51e9e6321caf5d23b2253f2415daf475fdaa417c0aa8fe896c3a460f2d023R130

**Pull request closed without merging**
